### ISSUE TITLE
Two fields not formatting

### ISSUE THREAD

**Issue by creativefibro** [Nurdok/booksidian#29]
The Series and abstract fields are not formatting correctly. I have tried removing them and re-adding them and refreshing the page but the problems continue.

<img width="1266" alt="CleanShot 2022-05-31 at 3 47 31@2x" src="https://user-images.githubusercontent.com/39191327/171202616-6c4f0cf7-e2f5-41cb-a98a-07d56e144b50.png">

**Comment by yoseft** [comment]
The issue was wrong handling of the case where there is no format and the are no spaces between the end of the parameter name and the first '}'. Fixed it now. In the mean-time, to resolve this issue, you can use "{{ series }}" and "{{ abstract }}" (instead of "{{series}}"/"{{abstract}} - add the spaces) in order to fix.
